$ANSIBLE_VAULT;1.1;AES256
65633165616438666538323166613961366533626263306338393166633362393339313032336637
3161313665356435306238663365663033623533623532350a646131633263626438353237393866
34333034613063633263663636623263303066623063383961393334313164633365626465323035
3436326466363761330a613465316338306531663936356433363263333831633362666537633237
64373539666463316161323363333061336133626263663236376463663664643236373730666634
31333538653437346464393334616136306530616630663430663264393836646136343430383365
30633461636134393366323636636366643236623431613830636533306539353366396435326334
33636537373631393131633537313638306363663664303139656634663637396535353336303439
37613165656238633264633064623463633264396163303533366562376363346565
