$ANSIBLE_VAULT;1.1;AES256
31353131373234306631393739373134303838303135636666323233323735333639353364336236
3864336237613932323139366366626432383230303438620a383662376431396630666661313130
32366539663264616364623531363034313265383533356163306439663265336366666635373539
3834336434616331650a386139653764336231333730353533316238336166326238303934333334
65663761333335656366653762383733643433306131393066356330313839303965356362353839
32376438653661386237623163643863666634646561376338633261313331643838396338376266
34333062646565343163643663353161383237376233323730376433383433643761333332646533
61643563653236633638653136306337313935626361313133663131643835616666653639346235
32393634383337626232316336353062363930316436366437366335393836343763
